#!/data/data/com.termux/files/usr/bin/bash

HMC::initializeVariable()
{
	declare -ax _HMC_colors;
	_HMC_colors[0]=$(printf "\e[0m");    # [ RESET ]
	_HMC_colors[1]=$(printf "\e[34m");   # [ DARK BLUE ]
	_HMC_colors[2]=$(printf "\e[32m");   # [ DARK GREEN ]
	_HMC_colors[3]=$(printf "\e[36m");   # [ DARK AQUA ]
	_HMC_colors[4]=$(printf "\e[31m");   # [ DARK RED ]
	_HMC_colors[5]=$(printf "\e[35m");   # [ DARK PURPLE ]
	_HMC_colors[6]=$(printf "\e[33m");   # [ GOLD ]
	_HMC_colors[7]=$(printf "\e[37m");   # [ GRAY ]
	_HMC_colors[8]=$(printf "\e[90m");   # [ DARK GRAY ]
	_HMC_colors[9]=$(printf "\e[94m");   # [ BLUE ]
	_HMC_colors[10]=$(printf "\e[30m");  # [ BLACK ]
	_HMC_colors[11]=$(printf "\e[92m");  # [ GREEN ]
	_HMC_colors[12]=$(printf "\e[94m");  # [ AQUA ]
	_HMC_colors[13]=$(printf "\e[91m");  # [ LIGHT RED ]
	_HMC_colors[14]=$(printf "\e[95m");  # [ PINK ]
	_HMC_colors[15]=$(printf "\e[93m");  # [ YELLOW ]
	_HMC_colors[16]=$(printf "\e[97m");  # [ WHITE ]
	_HMC_colors[17]=$(printf "\e[1m");  # [ BOLD TEXT ]
	_HMC_colors[18]=$(printf "\e[2m");  # [ FAINT TEXT ]
	_HMC_colors[19]=$(printf "\e[3m");  # [ ITALIC TEXT ]
	_HMC_colors[20]=$(printf "\e[4m");  # [ UNDERLINE TEXT ]
	_HMC_colors[21]=$(printf "\e[7m");  # [ REVERSE _HMC_colors ]
	_HMC_colors[22]=$(printf "\e[9m");  # [ STRIKETHROUGH TEXT ]
}
HMC::format()
{
	local rawText="$@";
	echo -e $(sed -r "s/§r/${_HMC_colors[0]}/g;s/§1/${_HMC_colors[1]}/g;s/§2/${_HMC_colors[2]}/g;s/§3/${_HMC_colors[3]}/g;s/§4/${_HMC_colors[4]}/g;s/§5/${_HMC_colors[5]}/g;s/§6/${_HMC_colors[6]}/g;s/§7/${_HMC_colors[7]}/g;s/§8/${_HMC_colors[8]}/g;s/§9/${_HMC_colors[9]}/g;s/§0/${_HMC_colors[10]}/g;s/§a/${_HMC_colors[11]}/g;s/§b/${_HMC_colors[12]}/g;s/§c/${_HMC_colors[13]}/g;s/§d/${_HMC_colors[14]}/g;s/§e/${_HMC_colors[15]}/g;s/§f/${_HMC_colors[16]}/g;s/§l/${_HMC_colors[17]}/g;s/§t/${_HMC_colors[18]}/g;s/§o/${_HMC_colors[19]}/g;s/§n/${_HMC_colors[20]}/g;s/§y/${_HMC_colors[21]}/g;s/§m/${_HMC_colors[22]}/g;" <<< $rawText);
}
HMC::msg()
{
	local text="§f[§l§dH§5M§eC§r]§7:§a $@§r";
	HMC::format $text;
}
HMC::warn()
{
	local text="§f[§l§dH§5M§eC§r]§7:§e $@§r"
	HMC::format $text;
}
HMC::error()
{
	local text="§f[§l§dH§5M§eC§r]§7:§c $@§r"
	HMC::format $text;
	exit 1;
}

HMC::update()
{
	apt-get update || return $?;
	apt-get -y -o Dpkg::Options::=--force-confdef upgrade || return $?;
}

#HMC::install(){}

HMC::initial()
{
	HMC::initializeVariable;
	#mkdir -p $HOME/.HMC && cd $HOME/.HMC;
	#touch errors.log installs.log
}
HMC::initial