#!/usr/bin/env bash

apt-get update && apt-get full-upgrade -y;
pkg i -y zip dnsutils termux-services whois tracepath traceroute wget git nmap termux-api openssh nodejs;
clear;
echo "Install completed"
