#!/usr/bin/env bash

apt-get update
pkg i -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
apt --fix-broken install
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
apt-get update
apt-get install -y mongodb-org
mongod --bind_ip 0.0.0.0 &
mongo --eval 'db.runCommand({ connectionStatus: 1 })'
