#!/bin/bash

# [ UPDATE & UPGRADE ]
curl -sL https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
[[ $? -gt 0 ]] && . .Himei/variables && _H::ERRS --no-warn;
. .Himei/variables;

# [ INSTALL UTILITIES ]
_H::MSGS 1 1 5;
pkg i $(_H::OPTS 2) $(_H::LIBS 1) 2> .Himei/error.log 1> .Himei/install.log || _H::ERRS --no-warn;
_H::MSGS 1 1 6;

# [ CLEAN ]
rm -rf .Himei;
