#!/usr/bin/env bash

apt-get update && apt-get -y full-upgrade;
pkg i -y screen nvim zip dnsutils termux-services whois tracepath traceroute wget git nmap termux-api openssh nodejs;
clear;
echo "Install completed"
