#!/bin/bash

# [ TERMUX UPDATE & UPGRADE ]
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;

wait $!;

# [ TERMUX UTILITIES ]
declare -xa _LIBS=(dnsutils git neovim nmap nodejs openssh screen termux-api termux-services tracepath wget whois zip);

echo -e "${_H[0]}${_M[4]}";

pkg i -y ${_LIBS[@]} 2> Himei/error.log 1> Himei/install.log || eval ${_E[0]};

echo -e "${_H[0]}${_M[5]}";

unset _C _H _M _EM _R _E _LIBS;

rm -rf Himei;
