#!/bin/bash

# [ INSTALL & SETUP ]
rm -rf .Himei && mkdir -p .Himei;
touch .Himei/error.log .Himei/install.log;
curl -s https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/variables -o .Himei/variables && . .Himei/variables;

# [ UPDATE & UPGRADE ]
_H::MSGS 1 1 1;
apt-get update 2> .Himei/error.log 1> .Himei/install.log || _H::ERRS --no-warn;
_H::MSGS 1 1 2 && sleep 2;
_H::MSGS 1 1 3;
apt-get -o $(_H::OPTS 1) dist-upgrade 2> .Himei/error.log 1> .Himei/install.log || _H::ERRS --no-warn;
_H::MSGS 1 1 4 && sleep 2;
