#!/bin/bash

# [ INSTALL & SETUP ]
rm -rf Himei && mkdir -p Himei;
touch Himei/error.log Himei/install.log;
curl https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/variables -o Himei/variables && . Himei/variables;

[[ $DEBUG == enabled ]] && eval "cat Himei/DEBUG 2> Himei/error.log || eval ${_E[0]}";

# [ UPDATE & UPGRADE ]
echo -e "${_M[1]}";
apt-get update 2> Himei/error.log 1> Himei/install.log || eval ${_E[0]};
echo -e "${_M[2]}" && sleep 2;
echo -e "${_M[3]}";
apt-get -o ${_O[0]} dist-upgrade 2> Himei/error.log 1> Himei/install.log || eval ${_E[0]};
echo -e "${_M[4]}" && sleep 2;
