#!/usr/bin/bash

_0=( "\e[0m" "\e[34m" "\e[32m" "\e[36m" "\e[31m" "\e[35m" "\e[33m" "\e[37m" "\e[90m" "\e[94m" "\e[30m" "\e[92m" "\e[94m" "\e[91m" "\e[95m" "\e[93m" "\e[97m" "\e[1;m" "\e[2;m" "\e[3;m" "\e[4;m" "\e[9;m" )

! [ -s "/etc/os-release" ] && exit 1

apt-get update
apt-get install -y gnupg nano
sed -i 's/jammy/focal/g' /etc/apt/sources.list
echo "Package: *
Pin: release a=focal
Pin-Priority: 1001" > /etc/apt/preferences
apt update && apt-get full-upgrade

[ $? -gt 0 ] && curl -L https://raw.githubusercontent.com/Miyu-Tenshi/install-setup/main/dpkg_repair | bash

wait
apt-get full-upgrade

rm '='

[ $? == 0 ] && eval "clear && echo -e \"${_0[15]}\$(cat /etc/os-release)\n${_0[14]}${_0[17]}HIMEI ${_0[8]}> ${_0[2]}INSTALL COMPLETED\"" || echo -e "${_0[14]}${_0[17]}HIMEI ${_0[8]}> ${_0[4]}INSTALL NOT COMPLETE"
