#!/bin/bash

# [ UPDATE & UPGRADE ]
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
[[ $? -gt 0 ]] && eval ${_E[0]};
. Himei/variables;

# [ INSTALL UBUNTU ]
_LIBS=(proot-distro);
echo -e "${_M[5]}";
pkg i ${_O[1]} ${_LIBS[@]} 2> Himei/error.log 1> Himei/install.log || eval ${_E[0]};
echo -e "${_M[6]}" && sleep 2;
echo -e "${_M[7]}";
proot-distro install ubuntu 2> Himei/error.log 1> Himei/install.log || eval ${_E[1]};
echo -e "${_M[8]}" && sleep 2;
echo -e "${_M[9]}";
proot-distro login ubuntu 2>&1 | grep -v "proot\swarning";

# [ UPDATE & UPGRADE ]
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
[[ $? -gt 0 ]] && eval ${_E[0]};
. Himei/variables;

sleep 3 && clear;
echo -e "${_M[10]}";
echo -e "${_M[11]}";

# [ CLEAN ]
rm -rf Himei;
exit 0;
rm -rf Himei;
