#!/bin/bash

# [ UBUNTU UPDATE & UPGRADE ]
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
[ $? -gt 0 ] && [ "$(cat Himei/error.log | grep -o 'dpkg')" == "dpkg" ] && curl -L https://raw.githubusercontent.com/Miyu-Tenshi/install-setup/main/dpkg_repair | bash

. Himei/variables;
! [ -e "/etc/os-release" ] && eval ${_E[3]};

# [ UBUNTU INSTALL & SETUP ]
declare -a _LIBS=(gnupg nano);
echo -e "${_H[0]}${_M[4]}";
pkg i --allow-downgrades -y ${_LIBS[@]} 2> Himei/error.log 1> Himei/install.log || eval ${_E[0]};
echo -e "${_H[0]}${_M[5]}";

sed -i 's/jammy/focal/g' /etc/apt/sources.list;
echo -e "Package: *\nPin: release a=focal\nPin-Priority: 1001" > /etc/apt/preferences

# [ UBUNTU UPDATE & UPGRADE ]
echo -e "${_H[0]}${_M[9]}";
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
[ $? -gt 0 ] && [ "$(cat Himei/error.log | grep -o 'dpkg')" == "dpkg" ] && curl -L https://raw.githubusercontent.com/Miyu-Tenshi/install-setup/main/dpkg_repair | bash
curl -L https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/termux_initial | bash;
echo -e "${_H[0]}${_M[10]}";
declare -a _INFOS=($(cat "/etc/os-release" | sed 's/^.*\=\|\"//g' | sed 's/\s/\_/g'));
_M[9]="Welcome to ${_INFOS[1]} ${_INFOS[3]//_/ }";
sleep 3 && clear;
echo -e "${_C[12]}${_M[9]}";

# [ CLEAN ]
unset _C _H _M _EM _R _E _LIBS;
rm -rf Himei;
