#!/bin/bash

declare -a _C=(); # [ COLORS ]
declare -a _H=(); # [ PREFIX ]
declare -a _M=(); # [ MESSAGES ]
declare -a _EM=(); # [ ERROR MESSAGES ]
declare -a _R=(); # [ REGULAR EXPRESSION ]
declare -a _E=(); # [ ERROR ]

_C[0]="\e[0m"; # [ RESET ]
_C[1]="\e[34m"; # [ DARK BLUE ]
_C[2]="\e[32m"; # [ DARK GREEN ]
_C[3]="\e[36m"; # [ DARK AQUA ]
_C[4]="\e[31m"; # [ DARK RED ]
_C[5]="\e[35m"; # [ DARK PURPLE ]
_C[6]="\e[33m"; # [ GOLD ]
_C[7]="\e[37m"; # [ GRAY ]
_C[8]="\e[90m"; # [ DARK GRAY ]
_C[9]="\e[94m"; # [ BLUE ]
_C[10]="\e[30m"; # [ BLACK ]
_C[11]="\e[92m"; # [ GREEN ]
_C[12]="\e[94m"; # [ AQUA ]
_C[13]="\e[91m"; # [ LIGHT RED ]
_C[14]="\e[95m"; # [ PINK ]
_C[15]="\e[93m"; # [ YELLOW ]
_C[16]="\e[97m"; # [ WHITE ]
_C[17]="\e[1;m"; # [ BOLD TEXT ]
_C[18]="\e[2;m"; # [ FAINT TEXT ]
_C[19]="\e[3;m"; # [ ITALIC TEXT ]
_C[20]="\e[4;m"; # [ UNDERLINE TEXT ]
_C[20]="\e[7;m"; # [ REVERSE COLOR ]
_C[21]="\e[9;m"; # [ STRIKETHROUGH TEXT ]

_H[0]="${_C[14]}${_C[17]}HIMEI ${_C[8]}> ";

_M[0]="";
_M[1]="${_H[0]}${_C[11]}Updating packages${_C[0]}";
_M[2]="${_H[0]}${_C[12]}Update packages completed${_C[0]}";
_M[3]="${_H[0]}${_C[11]}Installing packages${_C[0]}";
_M[4]="${_H[0]}${_C[12]}Install packages completed${_C[0]}";
_M[5]="${_H[0]}${_C[11]}Installing packages additional${_C[0]}";
_M[6]="${_H[0]}${_C[12]}Install packages additional completed${_C[0]}";
_M[7]="${_H[0]}${_C[11]}Installing ubuntu${_C[0]}";
_M[8]="${_H[0]}${_C[12]}Install ubuntu completed${_C[0]}";
_M[9]="${_H[0]}${_C[11]}Starting install packages ubuntu${_C[0]}";
_M[10]="${_H[0]}${_C[11]}Downgrading ubuntu${_C[0]}";
_M[11]="${_H[0]}${_C[12]}Downgrade ubuntu completed${_C[0]}";
_M[12]="${_H[0]}${_C[15]}Starting repair dpkg package${_C[0]}";
_M[13]="${_H[0]}${_C[15]}Repair dpkg package completed${_C[0]}";
_M[14]="${_H[0]}${_C[11]}Installing MongoDB CLI & Server${_C[0]}";
_M[15]="${_H[0]}${_C[12]}Install MongoDB completed${_C[0]}";

_EM[0]="${_H[0]}${_C[4]}Ubuntu is not installed${_C[0]}";
_EM[1]="${_H[0]}${_C[4]}This command can not run outside ubuntu${_C[0]}");

_R[0]="^$|WARNING";

_E[0]="sed -ri "/${_R[0]}/d" Himei/error.log";
_E[1]="echo -e "${_H[0]}${_C[4]}" && cat "Himei/error.log" && exit 1";
_E[2]="echo -e "${_EM[0]}" && exit 1";
_E[3]="echo -e "${_EM[1]}" && exit 1";
