#!/data/data/com.termux/files/usr/bin/bash

apt update;
apt -o Dpkg::Options::=--force-confdef --allow-downgrades -y dist-upgrade;
pkg i -y openssh;
sshd;
echo -e "\e[92mSSH is online\nplease create your password";
