#!/data/data/com.termux/files/usr/bin/bash

HMC::hmcSetup() {

    rm -rf termux-installs;

    pkg i -y git 1> /dev/null;

    git clone -q https://github.com/Miyu-Tenshi/termux-installs.git;

    return 0;
}

HMC::hmcSetup;