#!/data/data/com.termux/files/usr/bin/bash

HMC::installNginxCloudflareServer() {

    curl -sL https://raw.githubusercontent.com/Miyu-Tenshi/termux-installs/main/.HMC/templates/hmc-setup | bash;

    . "${HOME}/termux-installs/INSTALLS";

    HMC::initial;

    local tunnel_name;
    local url_website;

    read -p "Tunnel Name : " tunnel_name;
    
    wait;

    read -p "URL Website : " url_website;
    
    wait;

    echo "--== THIS ENDED ==--" && return 0;

    HMC::update --full;

    pkg i -y nginx cloudflared;

    cloudflared tunnel login;

    cloudflared tunnel create "${tunnel_name:-HMC-nginx}";

    cloudflared tunnel route dns "${tunnel_name:-HMC-nginx}" "${url_website:-hmc-nginx.com}";

    cloudflared tunnel --url http://localhost:8080 run "${tunnel_name:-HMC-nginx}";
}

HMC::installNginxCloudflareServer;