#!/data/data/com.termux/files/usr/bin/bash

HMC::installNginxCloudflareServer() {

    . "${HOME}/termux-installs/INSTALLS";

    HMC::initial;

    local tunnel_name;
    local url_website;

    read -p "Tunnel Name : " tunnel_name;
    read -p "URL Website : " url_website;

    HMC::update --full;

    pkg i -y nginx cloudflared;

    nginx;

    cloudflared tunnel login;
    
    wait;

    cloudflared tunnel create "$tunnel_name";
    [[ $? != 0 ]] && cloudflared tunnel delete "$tunnel_name" && cloudflared tunnel create "$tunnel_name";

    cloudflared tunnel route dns "$tunnel_name" "$url_website";

    cloudflared tunnel --url http://localhost:8080 run "$tunnel_name";
    #
    #cloudflared tunnel delete {tunnel_name}
    #cloudflared tunnel list
    # change session and can stop "nginx -s stop" to change root path location for nodejs server
}

HMC::installNginxCloudflareServer;