#!/data/data/com.termux/files/usr/bin/bash

cat > .HMC-setup << EOF
    echo -e "[\e7i] Updating packages";
    apt-get update &> /dev/null && echo -e "\e8✔] Update packages completed";
    echo -e "[\e7i] Upgrading packages";
    apt-get -o Dpkg::Options::=--force-confdef --allow-downgrades -y dist-upgrade &> /dev/null && echo -e "\e8✔] Upgrade packages completed";
    echo -e "[\e7i] Environments setup";
    export _HMC_PATH=$HOME/termux-installs/.HMC;
    export PATH=$PATH:$_HMC_PATH/bin;
    echo -e "\e8✔] Environments setup completed";
EOF